/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Dinuja pinto
 */
public class deleteCustomer extends javax.swing.JFrame {

    /**
     * Creates new form deleteCustomer
     */
    public deleteCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        dNic = new javax.swing.JTextField();
        btnDserch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Demail = new javax.swing.JTextField();
        Dname = new javax.swing.JTextField();
        Dphone = new javax.swing.JTextField();
        Daddress = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnDel = new javax.swing.JButton();
        btnDReset = new javax.swing.JButton();
        btnDclose = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/all page background image.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 220));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setText("Delete Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 21, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete buyer.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 12, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 78, 576, 10));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("NIC No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 105, -1, -1));

        dNic.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(dNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 99, 210, 31));

        btnDserch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDserch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/search.png"))); // NOI18N
        btnDserch.setText("Search");
        getContentPane().add(btnDserch, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 94, -1, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 139, 576, 10));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Phone");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        Demail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Demail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemailActionPerformed(evt);
            }
        });
        getContentPane().add(Demail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 245, 31));

        Dname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Dname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DnameActionPerformed(evt);
            }
        });
        getContentPane().add(Dname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 245, 31));

        Dphone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Dphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DphoneActionPerformed(evt);
            }
        });
        getContentPane().add(Dphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 245, 31));

        Daddress.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Daddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaddressActionPerformed(evt);
            }
        });
        getContentPane().add(Daddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 245, 31));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 576, 10));

        btnDel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btnDel.setText("Delete");
        getContentPane().add(btnDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, 40));

        btnDReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Reset.png"))); // NOI18N
        btnDReset.setText("Reset");
        btnDReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnDReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 40));

        btnDclose.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/close Jframe.png"))); // NOI18N
        btnDclose.setText("Close");
        btnDclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDcloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/all page background image.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DemailActionPerformed

    private void DnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DnameActionPerformed

    private void DphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DphoneActionPerformed

    private void DaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DaddressActionPerformed

    private void btnDcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDcloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnDcloseActionPerformed

    private void btnDResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDResetActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new deleteCustomer().setVisible(true);
    }//GEN-LAST:event_btnDResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deleteCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Daddress;
    private javax.swing.JTextField Demail;
    private javax.swing.JTextField Dname;
    private javax.swing.JTextField Dphone;
    private javax.swing.JButton btnDReset;
    private javax.swing.JButton btnDclose;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDserch;
    private javax.swing.JTextField dNic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
